### ISSUE TITLE
Allow 3.0 to be backwards compatible with < Node 8

### ISSUE THREAD

**Issue by pik** [darkguy2008/parallelshell#59]
Currently NPM does not allow specifying multiple versions of the same package (https://github.com/npm/npm/issues/5499) or determining which package to use based on engine version. 

Parallelshell existing in 2 incompatible variants is highly unsatisfactory, since this means developers have no good way to maintain working code for Node 8 as well as < Node 8 users. As far as I can tell from this commit https://github.com/keithamus/parallelshell/commit/11e1d29ad70e91df02ee4166edb04208bc53dfdf the only breaking change is `cwd / cwd()` that could be a quick `process.node.version > '8.0.0' ? process.cwd : process.cwd()`

**Comment by darkguy2008** [comment]
Hello!

I see, well, the < 2.1 version does work with < Node8, and 3.0+ with >= Node8, but then again you do have a point and it seems to be a small fix, although I don't like much to create a dependency by checking the runner's version inside a library, it's useful for node < 8 users.

I'm sorry I didn't add this before, I will do it right away. Thanks for your concern! 👍

**Comment by pik** [comment]
@darkguy2008 Thanks! It may seem uncommon in the JS ecosystem but e.g. with Python checking version is a pretty common way to make a single code-base / library compatible with both Python versions. I could provide a quick-patch if it's desired.

**Comment by darkguy2008** [comment]
@pik thanks for your insights, it makes sense now :). I've been a bit full these days and from what I could see, the variable should be process.versions.node... I could check if process.versions.node[0] == '8' but I'm not sure if that's okay... I'd need some time to set up different node envs to try. If you are able to make a patch, I'll happily review it and apply it immediately, what do you think? :D

**Comment by t3chguy** [comment]
@darkguy2008 @pik made a patch

**Comment by Nostradamos** [comment]
Did anyone try to contact @darkguy2008 on other channels?
Would love to see this PR merged.

**Comment by darkguy2008** [comment]
Hi all, sorry for the delay, I've been really busy with work but I got a notification here and set up some time to test and tidy up the repo a little bit. The PR has been merged, I need to update the packages and whatnot now 👍 thanks @pik !
