### ISSUE TITLE
child_process throwing error ('"cwd" must be a string')

### ISSUE THREAD

**Issue by gabrielbull** [darkguy2008/parallelshell#65]
As sen by others as well: https://github.com/darkguy2008/parallelshell/issues/57#issuecomment-388187159

```
TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
```

This bug was fixed for node 8.x but is present again in node 10.x

**Comment by darkguy2008** [comment]
Thanks for your bug report! I've pushed a fix now to the main branch, please give it a try :)

**Comment by williammizuta** [comment]
Can you release a new version with this fix?
