### ISSUE TITLE
The "options.cwd" property must be of type string. Received type function

### ISSUE THREAD

**Issue by FelixMH** [darkguy2008/parallelshell#73]
I have node 11.0.0 and I have this issue when I use yarn start because a internal command by parallelshell isn't work. I've been use npm-run-all and I've been use the last version of parallelshell and the issue is continue.

the complete error is :

**
child_process.js:417
throw new ERR_INVALID_ARG_TYPE('options.cwd', 'string', options.cwd);
^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received type function
at normalizeSpawnArguments (child_process.js:417:11)
at spawn (child_process.js:532:38)
**

can anybody help me please ?

**Comment by Matt-Kaminski** [comment]
I've updated node.js to 14.0 and got the same error. According to this:

https://github.com/darkguy2008/parallelshell/issues/69

I've edited node_modules/parallelshell/index.js file by changing this:

```
    var child = spawn(sh, [shFlag, cmd], {
        cwd: process.versions.node < '8.0.0' ? process.cwd : process.cwd(),
        env: process.env,
        stdio: ['pipe', process.stdout, process.stderr]
    })
```

to this:

```
    var child = spawn(sh, [shFlag, cmd], {
        //  cwd: process.versions.node < '8.0.0' ? process.cwd : process.cwd(),
        cwd: process.cwd(),
        env: process.env,
        stdio: ['pipe', process.stdout, process.stderr]
    })

```
It seems to work now.
